const ICONOS_POR_CATEGORIA = {
  alimentacion: 'mdi:food',
  'alimentacion-fuera-de-casa': 'mdi:silverware-fork-knife',
  alimentos: 'mdi:food',
  comida: 'mdi:food',
  restaurante: 'mdi:silverware-fork-knife',
  restaurantes: 'mdi:silverware-fork-knife',
  supermercado: 'mdi:cart-outline',
  mercado: 'mdi:cart-outline',
  transporte: 'mdi:bus',
  'transporte-publico': 'mdi:bus',
  gasolina: 'mdi:gas-station',
  combustible: 'mdi:gas-station',
  salud: 'mdi:medical-bag',
  medicamentos: 'mdi:medical-bag',
  farmacia: 'mdi:medical-bag',
  farmacias: 'mdi:medical-bag',
  educacion: 'mdi:school-outline',
  vivienda: 'mdi:home-outline',
  arriendo: 'mdi:home-currency-usd',
  servicios: 'mdi:receipt',
  'servicios-publicos': 'mdi:receipt',
  energia: 'mdi:lightning-bolt',
  luz: 'mdi:lightning-bolt',
  agua: 'mdi:water-outline',
  internet: 'mdi:wifi',
  telefono: 'mdi:cellphone',
  entretenimiento: 'mdi:movie-open-outline',
  cine: 'mdi:filmstrip',
  juegos: 'mdi:gamepad-variant-outline',
  salario: 'mdi:briefcase-outline',
  nomina: 'mdi:briefcase-outline',
  sueldo: 'mdi:briefcase-outline',
  ropa: 'mdi:tshirt-crew-outline',
  vestimenta: 'mdi:tshirt-crew-outline',
  shopping: 'mdi:shopping-outline',
  viajes: 'mdi:airplane',
  viaje: 'mdi:airplane',
  vacaciones: 'mdi:airplane',
  ahorro: 'mdi:piggy-bank',
  ahorros: 'mdi:piggy-bank',
  meta: 'mdi:piggy-bank',
  mascotas: 'mdi:paw',
  mascota: 'mdi:paw',
  regalos: 'mdi:gift-outline',
  regalo: 'mdi:gift-outline',
  donacion: 'mdi:heart-outline',
  impuestos: 'mdi:file-document-outline',
  deporte: 'mdi:dumbbell',
  gimnasio: 'mdi:dumbbell',
  gym: 'mdi:dumbbell',
};

const ICONO_DEFECTO = 'mdi:tag-outline';

const normalizar = (nombre = '') =>
  nombre.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim();

export const iconoDeCategoria = (nombreCategoria) =>
  ICONOS_POR_CATEGORIA[normalizar(nombreCategoria)] || ICONO_DEFECTO;